### PR TITLE
Interface to QORE

### PR DESCRIPTION
**Pull request by bnovoselnik**
- added QORE as a submodule (please note that QORE is in a private repo atm)
- added interface to QORE
- added mass spring example to test the interface

### CODE REVIEW

**Comment by bnovoselnik** [comment]
Travis is failing because it cannot access QORE repo :)

**Comment by dkouzoup** [comment]
I wish this was the only reason :P 

Travis is completely broken in new_core atm

**Comment by dkouzoup** [comment]
If you have some more time to kill, can you update your assign calculate_size functions to the latest format? i.e., using the dedicated functions from mem.c. Just pull new_core from here and see the qpoases interface

**Comment by dkouzoup** [comment]
Merged via terminal

**Pull request closed without merging**
